### ISSUE TITLE
Is there a way to start `rofi_trans` with some string as an argument to automatically translate it?

### ISSUE THREAD

**Issue by rizzini** [garyparrot/rofi-translate#2]
Title.

**Comment by garyparrot** [comment]
Thanks for open this issue, @rizzini.

`rofi_trans` currently doesn't support this feature. I poke around this ancient script for a while. I don't think there is an easy way to accomplish your goal. It feels like modify the source code is the only option. I managed to make it works at this [branch](https://github.com/garyparrot/rofi-translate/tree/pass-text-by-argument). Maybe you can take a look.

Here is how to use it.
1. ``env text="hello world" ./rofi_trans brief``
2. ``env text="hello world" ./rofi_trans verbose``
3. ``env text="hello world" ./rofi_trans delete``

The mode selector(brief, verbose, delete) used to be an optional argument but due to some complicated reason(the way ``rofi`` works), now you have to write out the mode selector specifically.

Parsing argument in shell script is complicated(not sure I didn't study it), so I keep using the environment variable to passing things. As always, if you like to improve or fix some of the issues in this ancient script, I am willing to review them.

This script is a little bit awkward since I was not good at shell script when I write this thing.  I just want a quick tool to help me study Englsih. So this script was born. Right now the codebase has become a maintenance nightmare. And some people actually using it. I never expect this to happen. Sorry for this bad code quality.

**Comment by rizzini** [comment]
Worked perfectly! When I have some time, I'll take a look and maybe I can contribute with something. Good job, man.
